### PR TITLE
Use exit code 0 when running in manual mode

### PR DESCRIPTION
**Pull request by jacksgt**
Hi,
thanks for this really nice and comprehensive project!

When running this container as a Kubernetes cronjob, it is really inconvenient that the script exits with return code "1", thereby marking the job as a failure.
Instead, the script should return "0" because everything was successful.

### CODE REVIEW

**Comment by tiredofit** [comment]
Agreed - this should have been 0 from the start. Much appreciated.

**Comment by jacksgt** [comment]
Great, thanks for merging so quickly!

**Comment by terryzwt** [comment]
Hi @jacksgt 
Could you share the yaml that you running this container on kubernetes?
I'm always concern that this container build-in cronjob conflict with kubernetes cronjob.
Thanks.

**Comment by jacksgt** [comment]
Hi Terry,
sure thing!
Here's the Cronjob YAML (the important part is `command: ["/bin/bash", "/etc/services.available/10-db-backup/run", "NOW"]`):

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/bash
            - /etc/services.available/10-db-backup/run
            - NOW
            envFrom:
            - secretRef:
                name: postgres-backup-pm2igcby
            image: docker.io/tiredofit/db-backup:2.11.3
            imagePullPolicy: IfNotPresent
            name: docker-db-backup
            volumeMounts:
            - mountPath: /tmp
              name: tmp
          volumes:
          - emptyDir: {}
            name: tmp
      ttlSecondsAfterFinished: 259200
  schedule: 14 1 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
```

And all the configuration is injected via this secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-xxx
  namespace: postgres
data:
  BACKUP_LOCATION: S3
  COMPRESSION: "true"
  COMPRESSION_LEVEL: "6"
  CONTAINER_ENABLE_MONITORING: "false"
  DB_HOST: xxx
  DB_PASS: xxx
  DB_PORT: xxx
  DB_TYPE: postgres
  DB_USER: xxx
  DEBUG_MODE: "false"
  MD5: "false"
  S3_BUCKET:xxx
  S3_HOST: xxx
  S3_KEY_ID: xxx
  S3_KEY_SECRET: xxx
  S3_PATH: xxx
  S3_REGION: xxx
  SPLIT_DB: "true"
```

I have this setup running for about a month for my Mariadb and Postgres instances and didn't have any issues so far.
Hope that helps!

**Comment by tiredofit** [comment]
This is an interesting use case now that I see this example. Do you think it would be beneficial to have a switch that turns it into manual mode only so that you can trigger it using your own cronjobs?

**Comment by terryzwt** [comment]
I think external support scheduler like kubernetes cronjob will be useful.

**Comment by tiredofit** [comment]
Thats certainly possible to do. Would you expect that after the container had performed its backup that the container shutdown? I can certainly make all the services turn off after a backup. The one thing is that there are features in here that one would need to turn off, specifically the in container cron scheduler (not related to db-backup, mostly related to logrotation, however since this image doesn't support file logs, its a moot point), and the in container zabbix monitoring agent. I could make it after the "manual" backup executed, it shut down all other services, or I could keep it up - and one would just have to execute the manual backup command again.  In fact, I can build both functions in, but I am just trying to see how others would use this.

**Comment by jacksgt** [comment]
> Thats certainly possible to do.

Thanks for considering to "officially" support this function (as you can see, it already kind of works now).

> Would you expect that after the container had performed its backup that the container shutdown?

Yes, it should cleanly exit with return code `0`.

> I can certainly make all the services turn off after a backup. The one thing is that there are features in here that one would need to turn off, specifically the in container cron scheduler (not related to db-backup, mostly related to logrotation, however since this image doesn't support file logs, its a moot point),

You also don't need any logrotation in a cronjob container, since it is ephemeral.

> and the in container zabbix monitoring agent. I could make it after the "manual" backup executed, it shut down all other services, or I could keep it up - and one would just have to execute the manual backup command again. In fact, I can build both functions in, but I am just trying to see how others would use this.

I'm honestly not sure how many people would the Zabbix agent + cronjob functionality. The most important signal for the scheduler is if the job ran successfully (`0`) or not (any other exit code).
Other monitoring systems (such as Prometheus) can then be triggered based on that.

I don't think much is needed for this functionality, maybe just a bit of documentation in the README :-)

**Comment by tiredofit** [comment]
README is updated with some guidance on using it in MODE=MANUAL - Hope this helps.

**Comment by terryzwt** [comment]
Using below config to run the docker container. after backup finished, it restart and continue to backup again.
What's the best practise?
`
    environment:
      - DEBUG_MODE=TRUE
      - MODE=MANUAL
      - MANUAL_RUN_FOREVER=TRUE
      - CONTAINER_ENABLE_SCHEDULING=FALSE
`

**Comment by terryzwt** [comment]
Ha, so quick response. Here is the full docker-compose.yml I'm using.
```
version: "3"
services:
  db-backup-manual:
    container_name: db-backup-manual
    image: tiredofit/db-backup
    volumes:
      - ./backup:/backup
    restart: always
    command: backup-now
    environment:
      - DEBUG_MODE=TRUE
      - MODE=MANUAL
      - MANUAL_RUN_FOREVER=TRUE
      - CONTAINER_ENABLE_SCHEDULING=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TIMEZONE=Asia/Shanghai
      - BACKUP_LOCATION=FILESYSTEM
      - DB_TYPE=mysql
      - DB_DUMP_TARGET=/backup
      - DB_HOST=example.com
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=1640
      - DB_CLEANUP_TIME=8640
      - ENABLE_CHECKSUM=FALSE
      - COMPRESSION=GZ
      - SPLIT_DB=TRUE
      - SIZE_VALUE=megabytes
      - ENABLE_SMTP=FALSE
      - ENABLE_ZABBIX=FALSE
      - ENABLE_LOGROTATE=FALSE
```

**Comment by tiredofit** [comment]
OK, those last 3 entries (ENABLE_*) are pretty old, so kudos to you for using my images for a couple years. They are no longer needed.

I'm going to try to recreate this in the morning, but can you answer my original question? You shouldn't be getting any backups when just starting up the container. It should only backup when executing `backup-now`, with yours, it should still keep the container up and running with `MANUAL_RUN_FOREVER=TRUE`.

**Comment by terryzwt** [comment]
I started container with `command: backup-now` and it keep looping backup.
If I start the container without `command: backup-now`, and `docker exec -it db-backup bash`, `backup-now`, it backup once which is correct.

**Comment by tiredofit** [comment]
Could it be in your docker-compose you have the declaration of `restart: always` ? I can't seem to recreate this with your two MANUAL_* environment variables.

**Comment by terryzwt** [comment]
good point. After disable `restart: always`, the backup does not loop now. Thanks for help!

**Pull request merged**
