### PR TITLE
Add cargo to build dependencies

### LINKED ISSUE #239: Explain dropping support for armv7 after 3.9.4
### Summary

I wanted to update the image on my raspberry pi 3 (armv7) from `3.9.1` to `3.9.7`, but I was greeted with the following error:

```shell
failed to solve: tiredofit/db-backup:3.9.7: no match for platform in manifest sha256:b86cd93ca0cd26d5d1bb1531ba34bb83ba3c156dd161ce9bab50e65d026ad31b: not found
```

So I took a look at the [dockerhub repo](https://hub.docker.com/r/tiredofit/db-backup/tags) and to my surprise all releases after (and including) `3.9.4` don't seem to have images for `armv7`.

Can you explain why was it changed in this [commit](https://github.com/tiredofit/docker-db-backup/commit/e71334564ffeb163fdd02f0c8e181d78447a7e1b) to no longer autobuild for `armv7` ?

### Environment

- Image version / tag:  `>=3.9.4`
- Host OS: Raspbian GNU/Linux 11 (bullseye); Model: Raspberry Pi 3 Model B

    
### Possible fixes

Enable autobuild for `armv7`.

### PR DESCRIPTION
**Pull request by ToshY**
Fixes #239

### CODE REVIEW

**Comment by ToshY** [comment]
Hey @tiredofit 👋 

If you have the time, could you review this PR?

**Review by tiredofit — APPROVED** [review]

**Comment by tiredofit** [comment]
Looks good to me! I will merge right now and merge a tagged release tomorrow.

**Comment by ToshY** [comment]
Hey @tiredofit 👋 

Reminder to tag a new release 🙂

**Comment by tiredofit** [comment]
OK! Tagged as `3.9.8` - Thanks for your patience.

**Pull request merged**
